package ar.com.svc.qr.model.constant;

public enum ConfigConstants {


    ID_COLUMN("ID"),
    CLIENT_CODE_COLUMN("CLIENT_CODE"),
    AUTH_URL_COLUMN("AUTH_URL"),
    VALIDATE_URL_COLUMN("VALIDATE_URL"),
    SIZE_COLUMN("SIZE"),
    TTL_COLUMNN("TTL"),
    CREATED_BY_COLUMN("CREATED_BY"),
    CREATED_DATE_COLUMN("CREATED_DATE"),

    FIND_ALL_QUERY("SELECT * FROM AUTH.CONFIG"),
    FIND_BY_ID_QUERY("SELECT * FROM AUTH.CONFIG WHERE ID=?"),
    FIND_BY_CLIENT_CODE_QUERY("SELECT * FROM AUTH.CONFIG WHERE CLIENT_CODE=?"),
    EXISTS_QUERY("SELECT COUNT(*) FROM AUTH.CONFIG WHERE CLIENT_CODE=?"),
    INSERT_QUERY("INSERT INTO AUTH.CONFIG (CLIENT_CODE, AUTH_URL, VALIDATE_URL, SIZE, TTL, CREATED_BY) VALUES (?, ?, ?, ?, ?, ?)"),
    INSERT_OR_UPDATE_QUERY("INSERT INTO AUTH.CONFIG (CLIENT_CODE, AUTH_URL, VALIDATE_URL, SIZE, TTL, CREATED_BY) VALUES (?, ?, ?, ?, ?, ?) \n" +
            "ON DUPLICATE KEY UPDATE CLIENT_CODE=?, AUTH_URL=?, VALIDATE_URL=?, SIZE=?, TTL=?"),
    DELETE_BY_ID_QUERY("DELETE FROM AUTH.CONFIG WHERE ID=?"),
    DELETE_BY_CLIENT_CODE_QUERY("DELETE FROM AUTH.CONFIG WHERE CLIENT_CODE=?"),
    DELETE_ALL_QUERY("DELETE FROM AUTH.CONFIG"),
    UPDATE_BY_ID_QUERY("UPDATE AUTH.CONFIG SET AUTH_URL=?, VALIDATE_URL=?, SIZE=?, TTL=? WHERE ID=?"),
    UPDATE_BY_CLIENT_CODE_QUERY("UPDATE AUTH.CONFIG SET AUTH_URL=?, VALIDATE_URL=?, SIZE=?, TTL=? WHERE CLIENT_CODE=?");


    private final String value;

    ConfigConstants(String value) {
        this.value = value;
    }

    public String getValue() {
        return value;
    }
}
