package ar.com.svc.qr.model.constant;

public enum UserConstants {


    ID_COLUMN("ID"),
    FULL_NAME_COLUMN("FULL_NAME"),
    USERNAME_COLUMN("USERNAME"),
    PASSWORD_COLUMN("PASSWORD"),
    EMAIL_COLUMN("EMAIL"),
    ROLE_COLUMN("ROLE"),
    CREATED_DATE_COLUMN("CREATED_DATE"),

    FIND_ALL_QUERY("SELECT * FROM AUTH.USER"),
    FIND_BY_ID_QUERY("SELECT * FROM AUTH.USER WHERE ID=?"),
    FIND_BY_USERNAME_QUERY("SELECT * FROM AUTH.USER WHERE USERNAME=?"),
    EXISTS_QUERY("SELECT COUNT(*) FROM AUTH.USER WHERE USERNAME=?"),
    VALIDATE_USER_QUERY("SELECT * FROM AUTH.USER WHERE USERNAME=? AND PASSWORD=SHA1(?)"),
    INSERT_QUERY("INSERT INTO AUTH.USER (USERNAME, FULL_NAME, PASSWORD, EMAIL, ROLE) VALUES (?, ?, SHA1(?), ?, ?)"),
    INSERT_OR_UPDATE_QUERY("INSERT INTO AUTH.USER (USERNAME, FULL_NAME, EMAIL, ROLE) VALUES (?, ?, ?, ?)\n" +
            "ON DUPLICATE KEY UPDATE USERNAME=?, FULL_NAME=?, EMAIL=?, ROLE=?"),
    DELETE_BY_ID_QUERY("DELETE FROM AUTH.USER WHERE ID=?"),
    DELETE_BY_USERNAME_QUERY("DELETE FROM AUTH.USER WHERE USERNAME=?"),
    DELETE_ALL_QUERY("DELETE FROM AUTH.USER"),
    UPDATE_BY_ID_QUERY("UPDATE AUTH.USER SET FULL_NAME=?, EMAIL=?, ROLE=? WHERE ID=?"),
    UPDATE_BY_USERNAME_QUERY("UPDATE AUTH.USER SET FULL_NAME=?, EMAIL=?, ROLE=? WHERE USERNAME=?");

    private final String value;

    UserConstants(String value) {
        this.value = value;
    }

    public String getValue() {
        return value;
    }
}
