DROP SCHEMA AUTH;

CREATE DATABASE IF NOT EXISTS AUTH;

USE AUTH;

CREATE TABLE IF NOT EXISTS AUTH.USER_CODES (
  CLIENT_CODE BIGINT NOT NULL,
  TOKEN VARCHAR(30) NOT NULL,
  UUID VARCHAR(16) NOT NULL,
  CREATED_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE AUTH.USER_CODES ADD UNIQUE KEY(TOKEN, CLIENT_CODE);
ALTER TABLE AUTH.USER_CODES ADD ID BIGINT UNIQUE NOT NULL AUTO_INCREMENT FIRST;
ALTER TABLE AUTH.USER_CODES ADD INDEX TOKEN_UC_IDX (TOKEN ASC);
ALTER TABLE AUTH.USER_CODES ADD INDEX CLIENT_CODE__UC_IDX (CLIENT_CODE ASC);
ALTER TABLE AUTH.USER_CODES ADD UNIQUE INDEX UUID_UC_IDX (UUID ASC);

CREATE TABLE IF NOT EXISTS AUTH.CONFIG (
  CLIENT_CODE VARCHAR(30) NOT NULL,
  AUTH_URL TEXT NOT NULL,
  VALIDATE_URL TEXT NOT NULL,
  SIZE INT NOT NULL,
  TTL MEDIUMINT NOT NULL DEFAULT 0,
  CREATED_BY BIGINT NOT NULL,
  CREATED_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE AUTH.CONFIG ADD UNIQUE KEY(CLIENT_CODE);
ALTER TABLE AUTH.CONFIG ADD ID BIGINT UNIQUE NOT NULL AUTO_INCREMENT FIRST;
ALTER TABLE AUTH.CONFIG ADD INDEX CLIENT_CODE_CONFIG_IDX (CLIENT_CODE ASC);

CREATE TABLE IF NOT EXISTS AUTH.USER (
  USERNAME VARCHAR(30) NOT NULL,
  FULL_NAME TEXT NOT NULL,
  PASSWORD TEXT NOT NULL,
  EMAIL VARCHAR(50) NOT NULL,
  ROLE INT NOT NULL,
  CREATED_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE AUTH.USER ADD UNIQUE KEY(USERNAME);
ALTER TABLE AUTH.USER ADD ID BIGINT UNIQUE NOT NULL AUTO_INCREMENT FIRST;
ALTER TABLE AUTH.USER ADD INDEX USERNAME_USER_IDX (USERNAME ASC);

INSERT INTO AUTH.CONFIG (CLIENT_CODE, AUTH_URL, VALIDATE_URL, SIZE, TTL, CREATED_BY) VALUES ('cctest1', 'http://0.0.0.0:8090/api/dummy/token', 'http://0.0.0.0:8090/api/dummy/validate', 50, 3600, 1);

INSERT INTO AUTH.USER (USERNAME, FULL_NAME, PASSWORD, EMAIL, ROLE) VALUES ('test1', 'test uno', SHA1('12345678'), 'test1@gmail.com', 0);
INSERT INTO AUTH.USER (USERNAME, FULL_NAME, PASSWORD, EMAIL, ROLE) VALUES ('test2', 'test dos', SHA1('12345678'), 'test2@gmail.com', 1);
