INSERT INTO "AUTH"."USER_CODES" (CLIENT_CODE, TOKEN, UUID) VALUES (0, 'usertoken1', 'AXC472FV6YTP96BM');
INSERT INTO "AUTH"."USER_CODES" (CLIENT_CODE, TOKEN, UUID) VALUES (0, 'usertoken3', 'NZC472FV6YTP96BM');

INSERT INTO "AUTH"."CONFIG" (CLIENT_CODE, AUTH_URL, VALIDATE_URL, SIZE, TTL, CREATED_BY) VALUES ('cctest1', 'http://0.0.0.0:8090/api/dummy/token', 'http://0.0.0.0:8090/api/dummy/validate', 50, 3600, 1);

INSERT INTO "AUTH"."USER" (USERNAME, FULL_NAME, PASSWORD, EMAIL, ROLE) VALUES ('test1', 'test uno', '12345678', 'test1@gmail.com', 0);
INSERT INTO "AUTH"."USER" (USERNAME, FULL_NAME, PASSWORD, EMAIL, ROLE) VALUES ('test2', 'test dos', '12345678', 'test2@gmail.com', 1);
